# Generated by Django 2.2.2 on 2019-07-19 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DownloadDocount', models.IntegerField(default=0, verbose_name='下载次数')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('Datatime', models.DateTimeField(default=datetime.datetime.now)),
                ('path', models.CharField(max_length=32, verbose_name='下载路径')),
                ('name', models.CharField(default='', max_length=32, verbose_name='文件名')),
                ('Filesize', models.CharField(max_length=10, verbose_name='文件大小')),
                ('PCIP', models.CharField(default='', max_length=32, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': 'download',
                'verbose_name_plural': 'download',
                'db_table': 'download',
            },
        ),
    ]
